// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: telemetry.proto

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Core enumeration defining what kind of device is reporting metrics
type DeviceType int32

const (
	DeviceType_DEVICE_TYPE_UNSPECIFIED    DeviceType = 0
	DeviceType_DEVICE_TYPE_SMART_METER    DeviceType = 1
	DeviceType_DEVICE_TYPE_BATTERY_BMS    DeviceType = 2
	DeviceType_DEVICE_TYPE_SOLAR_INVERTER DeviceType = 3
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "DEVICE_TYPE_UNSPECIFIED",
		1: "DEVICE_TYPE_SMART_METER",
		2: "DEVICE_TYPE_BATTERY_BMS",
		3: "DEVICE_TYPE_SOLAR_INVERTER",
	}
	DeviceType_value = map[string]int32{
		"DEVICE_TYPE_UNSPECIFIED":    0,
		"DEVICE_TYPE_SMART_METER":    1,
		"DEVICE_TYPE_BATTERY_BMS":    2,
		"DEVICE_TYPE_SOLAR_INVERTER": 3,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_proto_enumTypes[0].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_telemetry_proto_enumTypes[0]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

// Sub-message grouping raw electrical metrics
type ElectricalMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voltage       float32                `protobuf:"fixed32,1,opt,name=voltage,proto3" json:"voltage,omitempty"`                            // Volts (V)
	Current       float32                `protobuf:"fixed32,2,opt,name=current,proto3" json:"current,omitempty"`                            // Amperes (A)
	ActivePower   float32                `protobuf:"fixed32,3,opt,name=active_power,json=activePower,proto3" json:"active_power,omitempty"` // Kilowatts (kW)
	Frequency     float32                `protobuf:"fixed32,4,opt,name=frequency,proto3" json:"frequency,omitempty"`                        // Hertz (Hz)
	TotalKwh      float64                `protobuf:"fixed64,5,opt,name=total_kwh,json=totalKwh,proto3" json:"total_kwh,omitempty"`          // Cumulative Kilowatt-hours (kWh) for billing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElectricalMetrics) Reset() {
	*x = ElectricalMetrics{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectricalMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectricalMetrics) ProtoMessage() {}

func (x *ElectricalMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectricalMetrics.ProtoReflect.Descriptor instead.
func (*ElectricalMetrics) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *ElectricalMetrics) GetVoltage() float32 {
	if x != nil {
		return x.Voltage
	}
	return 0
}

func (x *ElectricalMetrics) GetCurrent() float32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *ElectricalMetrics) GetActivePower() float32 {
	if x != nil {
		return x.ActivePower
	}
	return 0
}

func (x *ElectricalMetrics) GetFrequency() float32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *ElectricalMetrics) GetTotalKwh() float64 {
	if x != nil {
		return x.TotalKwh
	}
	return 0
}

// The master telemetry packet sent by edge hardware into the pipeline
type MetricPayload struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	DeviceId     string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                                           // Unique physical hardware identifier (e.g., "met-5540")
	DeviceType   DeviceType             `protobuf:"varint,2,opt,name=device_type,json=deviceType,proto3,enum=ambagrid.telemetry.DeviceType" json:"device_type,omitempty"` // Type of physical appliance sending data
	TimestampUtc int64                  `protobuf:"varint,3,opt,name=timestamp_utc,json=timestampUtc,proto3" json:"timestamp_utc,omitempty"`                              // Unix epoch timestamp in seconds
	// --- The Ontology Linkage Layer ---
	// Passing these relations down the wire helps the Rust engine speed up graph traversals
	SiteId      string `protobuf:"bytes,4,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`                // The Mini-Grid facility identifier (e.g., "ng-kaji-01")
	HouseholdId string `protobuf:"bytes,5,opt,name=household_id,json=householdId,proto3" json:"household_id,omitempty"` // Optional: Connects smart meters directly to physical properties
	// --- Real-Time Hardware Sensor Diagnostics ---
	Metrics             *ElectricalMetrics `protobuf:"bytes,6,opt,name=metrics,proto3" json:"metrics,omitempty"`
	InternalTemperature float32            `protobuf:"fixed32,7,opt,name=internal_temperature,json=internalTemperature,proto3" json:"internal_temperature,omitempty"` // Celsius (°C) to trigger fire/overheating rules
	RelayClosed         bool               `protobuf:"varint,8,opt,name=relay_closed,json=relayClosed,proto3" json:"relay_closed,omitempty"`                          // True = Power is active, False = Customer is disconnected
	// --- Battery/Inverter Specialized States (Populated based on DeviceType) ---
	BatterySocPct   float32 `protobuf:"fixed32,9,opt,name=battery_soc_pct,json=batterySocPct,proto3" json:"battery_soc_pct,omitempty"`      // State of Charge (0.0 to 100.0%) for BMS nodes
	SolarIrradiance float32 `protobuf:"fixed32,10,opt,name=solar_irradiance,json=solarIrradiance,proto3" json:"solar_irradiance,omitempty"` // W/m² input reading for solar inverter arrays
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetricPayload) Reset() {
	*x = MetricPayload{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPayload) ProtoMessage() {}

func (x *MetricPayload) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPayload.ProtoReflect.Descriptor instead.
func (*MetricPayload) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *MetricPayload) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *MetricPayload) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *MetricPayload) GetTimestampUtc() int64 {
	if x != nil {
		return x.TimestampUtc
	}
	return 0
}

func (x *MetricPayload) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *MetricPayload) GetHouseholdId() string {
	if x != nil {
		return x.HouseholdId
	}
	return ""
}

func (x *MetricPayload) GetMetrics() *ElectricalMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *MetricPayload) GetInternalTemperature() float32 {
	if x != nil {
		return x.InternalTemperature
	}
	return 0
}

func (x *MetricPayload) GetRelayClosed() bool {
	if x != nil {
		return x.RelayClosed
	}
	return false
}

func (x *MetricPayload) GetBatterySocPct() float32 {
	if x != nil {
		return x.BatterySocPct
	}
	return 0
}

func (x *MetricPayload) GetSolarIrradiance() float32 {
	if x != nil {
		return x.SolarIrradiance
	}
	return 0
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\x12ambagrid.telemetry\"\xa5\x01\n" +
	"\x11ElectricalMetrics\x12\x18\n" +
	"\avoltage\x18\x01 \x01(\x02R\avoltage\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\x02R\acurrent\x12!\n" +
	"\factive_power\x18\x03 \x01(\x02R\vactivePower\x12\x1c\n" +
	"\tfrequency\x18\x04 \x01(\x02R\tfrequency\x12\x1b\n" +
	"\ttotal_kwh\x18\x05 \x01(\x01R\btotalKwh\"\xb8\x03\n" +
	"\rMetricPayload\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12?\n" +
	"\vdevice_type\x18\x02 \x01(\x0e2\x1e.ambagrid.telemetry.DeviceTypeR\n" +
	"deviceType\x12#\n" +
	"\rtimestamp_utc\x18\x03 \x01(\x03R\ftimestampUtc\x12\x17\n" +
	"\asite_id\x18\x04 \x01(\tR\x06siteId\x12!\n" +
	"\fhousehold_id\x18\x05 \x01(\tR\vhouseholdId\x12?\n" +
	"\ametrics\x18\x06 \x01(\v2%.ambagrid.telemetry.ElectricalMetricsR\ametrics\x121\n" +
	"\x14internal_temperature\x18\a \x01(\x02R\x13internalTemperature\x12!\n" +
	"\frelay_closed\x18\b \x01(\bR\vrelayClosed\x12&\n" +
	"\x0fbattery_soc_pct\x18\t \x01(\x02R\rbatterySocPct\x12)\n" +
	"\x10solar_irradiance\x18\n" +
	" \x01(\x02R\x0fsolarIrradiance*\x83\x01\n" +
	"\n" +
	"DeviceType\x12\x1b\n" +
	"\x17DEVICE_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DEVICE_TYPE_SMART_METER\x10\x01\x12\x1b\n" +
	"\x17DEVICE_TYPE_BATTERY_BMS\x10\x02\x12\x1e\n" +
	"\x1aDEVICE_TYPE_SOLAR_INVERTER\x10\x03B1Z/ingestion-go/proto/ambagrid/telemetry;telemetryb\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_telemetry_proto_goTypes = []any{
	(DeviceType)(0),           // 0: ambagrid.telemetry.DeviceType
	(*ElectricalMetrics)(nil), // 1: ambagrid.telemetry.ElectricalMetrics
	(*MetricPayload)(nil),     // 2: ambagrid.telemetry.MetricPayload
}
var file_telemetry_proto_depIdxs = []int32{
	0, // 0: ambagrid.telemetry.MetricPayload.device_type:type_name -> ambagrid.telemetry.DeviceType
	1, // 1: ambagrid.telemetry.MetricPayload.metrics:type_name -> ambagrid.telemetry.ElectricalMetrics
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		EnumInfos:         file_telemetry_proto_enumTypes,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
